num1=float(input('Digite um número: '))
num2=float(input('Digite um número: '))
num3=float(input('Digite um número: '))
num4=float(input('Digite um número: '))
num5=float(input('Digite um número: '))
media = (num1 + num2 + num3 + num4 + num5/5)
print(f'Media :{media}')